#############################################################################
# Makefile for building: gui
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  QtBase-001.pro
# Template: app
# Command: /bin/qmake -o Makefile QtBase-001.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGIT_VERSION=\"\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -fdiagnostics-color=auto -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fdiagnostics-color=auto -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/qwt -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/../lib64/qt5/mkspecs/linux-g++
QMAKE         = /bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /bin/qmake -install qinstall
QINSTALL_PROGRAM = /bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gui1.0.0
DISTDIR = /home/dai/ActiveProjects/ZXP24-PC-GUI/.tmp/gui1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lm -lmirsdrapi-rsp -lfftw3 -lluaradio -lluajit-5.1 -Wl,-E -lliquid -lasound /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Main.cpp \
		MainWindow.cpp \
		ScopePlotter.cpp \
		adpcm.c \
		cfreqctrl.cpp \
		meter.cpp \
		Rxr.cpp moc_MainWindow.cpp \
		moc_ScopePlotter.cpp \
		moc_cfreqctrl.cpp \
		moc_meter.cpp \
		moc_Rxr.cpp
OBJECTS       = Main.o \
		MainWindow.o \
		ScopePlotter.o \
		adpcm.o \
		cfreqctrl.o \
		meter.o \
		Rxr.o \
		moc_MainWindow.o \
		moc_ScopePlotter.o \
		moc_cfreqctrl.o \
		moc_meter.o \
		moc_Rxr.o
DIST          = /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		QtBase-001.pro MainWindow.h \
		ScopePlotter.h \
		cfreqctrl.h \
		meter.h \
		Rxr.h Main.cpp \
		MainWindow.cpp \
		ScopePlotter.cpp \
		adpcm.c \
		cfreqctrl.cpp \
		meter.cpp \
		Rxr.cpp
QMAKE_TARGET  = gui
DESTDIR       = 
TARGET        = gui


first: all
####### Build rules

gui: ui_QtBase-001.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtBase-001.pro /../lib64/qt5/mkspecs/linux-g++/qmake.conf /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		QtBase-001.pro
	$(QMAKE) -o Makefile QtBase-001.pro
/../lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/../lib64/qt5/mkspecs/qconfig.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/../lib64/qt5/mkspecs/features/qt_functions.prf:
/../lib64/qt5/mkspecs/features/qt_config.prf:
/../lib64/qt5/mkspecs/linux-g++/qmake.conf:
/../lib64/qt5/mkspecs/features/spec_post.prf:
/../lib64/qt5/mkspecs/features/exclusive_builds.prf:
/../lib64/qt5/mkspecs/features/toolchain.prf:
/../lib64/qt5/mkspecs/features/default_pre.prf:
/../lib64/qt5/mkspecs/features/resolve_config.prf:
/../lib64/qt5/mkspecs/features/default_post.prf:
/../lib64/qt5/mkspecs/features/warn_on.prf:
/../lib64/qt5/mkspecs/features/qt.prf:
/../lib64/qt5/mkspecs/features/resources_functions.prf:
/../lib64/qt5/mkspecs/features/resources.prf:
/../lib64/qt5/mkspecs/features/moc.prf:
/../lib64/qt5/mkspecs/features/unix/opengl.prf:
/../lib64/qt5/mkspecs/features/uic.prf:
/../lib64/qt5/mkspecs/features/unix/thread.prf:
/../lib64/qt5/mkspecs/features/qmake_use.prf:
/../lib64/qt5/mkspecs/features/file_copies.prf:
/../lib64/qt5/mkspecs/features/testcase_targets.prf:
/../lib64/qt5/mkspecs/features/exceptions.prf:
/../lib64/qt5/mkspecs/features/yacc.prf:
/../lib64/qt5/mkspecs/features/lex.prf:
QtBase-001.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile QtBase-001.pro

qmake_all: FORCE


all: Makefile gui

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainWindow.h ScopePlotter.h cfreqctrl.h meter.h Rxr.h $(DISTDIR)/
	$(COPY_FILE) --parents Main.cpp MainWindow.cpp ScopePlotter.cpp adpcm.c cfreqctrl.cpp meter.cpp Rxr.cpp $(DISTDIR)/
	$(COPY_FILE) --parents QtBase-001.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -fdiagnostics-color=auto -O2 -Wall -Wextra -dM -E -o moc_predefs.h /../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_ScopePlotter.cpp moc_cfreqctrl.cpp moc_meter.cpp moc_Rxr.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_ScopePlotter.cpp moc_cfreqctrl.cpp moc_meter.cpp moc_Rxr.cpp
moc_MainWindow.cpp: MainWindow.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/dai/ActiveProjects/ZXP24-PC-GUI/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/qwt -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_ScopePlotter.cpp: ScopePlotter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/dai/ActiveProjects/ZXP24-PC-GUI/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/qwt -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include ScopePlotter.h -o moc_ScopePlotter.cpp

moc_cfreqctrl.cpp: cfreqctrl.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/dai/ActiveProjects/ZXP24-PC-GUI/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/qwt -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include cfreqctrl.h -o moc_cfreqctrl.cpp

moc_meter.cpp: meter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/dai/ActiveProjects/ZXP24-PC-GUI/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/qwt -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include meter.h -o moc_meter.cpp

moc_Rxr.cpp: Rxr.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/dai/ActiveProjects/ZXP24-PC-GUI/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/home/dai/ActiveProjects/ZXP24-PC-GUI -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/qwt -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include Rxr.h -o moc_Rxr.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_QtBase-001.h
compiler_uic_clean:
	-$(DEL_FILE) ui_QtBase-001.h
ui_QtBase-001.h: QtBase-001.ui \
		/../lib64/qt5/bin/uic \
		ScopePlotter.h \
		cfreqctrl.h \
		meter.h
	/../lib64/qt5/bin/uic QtBase-001.ui -o ui_QtBase-001.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Main.o: Main.cpp MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_QtBase-001.h \
		Rxr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

ScopePlotter.o: ScopePlotter.cpp ScopePlotter.h \
		waterfall.h \
		Rxr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScopePlotter.o ScopePlotter.cpp

adpcm.o: adpcm.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o adpcm.o adpcm.c

cfreqctrl.o: cfreqctrl.cpp cfreqctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cfreqctrl.o cfreqctrl.cpp

meter.o: meter.cpp meter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meter.o meter.cpp

Rxr.o: Rxr.cpp MainWindow.h \
		Rxr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rxr.o Rxr.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_ScopePlotter.o: moc_ScopePlotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScopePlotter.o moc_ScopePlotter.cpp

moc_cfreqctrl.o: moc_cfreqctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cfreqctrl.o moc_cfreqctrl.cpp

moc_meter.o: moc_meter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meter.o moc_meter.cpp

moc_Rxr.o: moc_Rxr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Rxr.o moc_Rxr.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

